"""Add vulnerabilities table

Revision ID: 874d67e7b43c
Revises: 005
Create Date: 2026-02-17 13:36:00.388807+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "874d67e7b43c"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vulnerabilities_created_at"), table_name="vulnerabilities")
    op.drop_index(
        op.f("ix_vulnerabilities_repository_id"), table_name="vulnerabilities"
    )
    op.drop_index(op.f("ix_vulnerabilities_severity"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_type"), table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.create_index(
        op.f("ix_call_relationships_callee_symbol_id"),
        "call_relationships",
        ["callee_symbol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_call_relationships_caller_symbol_id"),
        "call_relationships",
        ["caller_symbol_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_call_relationships_id"), "call_relationships", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_call_relationships_repository_id"),
        "call_relationships",
        ["repository_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("call_relationships_repository_id_fkey"),
        "call_relationships",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("call_relationships_callee_symbol_id_fkey"),
        "call_relationships",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("call_relationships_caller_symbol_id_fkey"),
        "call_relationships",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "call_relationships", "repositories", ["repository_id"], ["id"]
    )
    op.create_foreign_key(
        None, "call_relationships", "symbols", ["callee_symbol_id"], ["id"]
    )
    op.create_foreign_key(
        None, "call_relationships", "symbols", ["caller_symbol_id"], ["id"]
    )
    op.create_foreign_key(
        None, "embeddings", "symbols", ["symbol_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column("files", "line_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "repositories",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "processing", "completed", "failed", name="repostatus"
        ),
        nullable=False,
    )
    op.alter_column(
        "repositories", "file_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "repositories", "symbol_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(op.f("idx_repositories_source"), table_name="repositories")
    op.create_index(
        op.f("ix_repositories_source"), "repositories", ["source"], unique=False
    )
    op.alter_column(
        "symbols",
        "signature",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_symbols_complexity"), table_name="symbols")
    op.create_index(
        op.f("ix_symbols_cyclomatic_complexity"),
        "symbols",
        ["cyclomatic_complexity"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_symbols_cyclomatic_complexity"), table_name="symbols")
    op.create_index(
        op.f("idx_symbols_complexity"),
        "symbols",
        ["cyclomatic_complexity"],
        unique=False,
    )
    op.alter_column(
        "symbols",
        "signature",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_repositories_source"), table_name="repositories")
    op.create_index(
        op.f("idx_repositories_source"), "repositories", ["source"], unique=False
    )
    op.alter_column(
        "repositories", "symbol_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "repositories", "file_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "repositories",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "processing", "completed", "failed", name="repostatus"
        ),
        nullable=True,
    )
    op.alter_column("files", "line_count", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "embeddings", type_="foreignkey")
    op.drop_constraint(None, "call_relationships", type_="foreignkey")
    op.drop_constraint(None, "call_relationships", type_="foreignkey")
    op.drop_constraint(None, "call_relationships", type_="foreignkey")
    op.create_foreign_key(
        op.f("call_relationships_caller_symbol_id_fkey"),
        "call_relationships",
        "symbols",
        ["caller_symbol_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("call_relationships_callee_symbol_id_fkey"),
        "call_relationships",
        "symbols",
        ["callee_symbol_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("call_relationships_repository_id_fkey"),
        "call_relationships",
        "repositories",
        ["repository_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_call_relationships_repository_id"), table_name="call_relationships"
    )
    op.drop_index(op.f("ix_call_relationships_id"), table_name="call_relationships")
    op.drop_index(
        op.f("ix_call_relationships_caller_symbol_id"), table_name="call_relationships"
    )
    op.drop_index(
        op.f("ix_call_relationships_callee_symbol_id"), table_name="call_relationships"
    )
    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "severity", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("cwe_id", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "owasp_category", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "file_path", sa.VARCHAR(length=1000), autoincrement=False, nullable=False
        ),
        sa.Column("line_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("code_snippet", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("recommendation", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "confidence", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("vulnerabilities_repository_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("vulnerabilities_pkey")),
    )
    op.create_index(
        op.f("ix_vulnerabilities_type"), "vulnerabilities", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerabilities_severity"),
        "vulnerabilities",
        ["severity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_repository_id"),
        "vulnerabilities",
        ["repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_created_at"),
        "vulnerabilities",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
