"""Add metrics_snapshots table

Revision ID: f51a6709cc45
Revises: 20260219_add_docstring_tracking
Create Date: 2026-02-19 15:33:17.691408+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f51a6709cc45'
down_revision: Union[str, None] = '20260219_add_docstring_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_call_relationships_callee_symbol_id'), 'call_relationships', ['callee_symbol_id'], unique=False)
    op.create_index(op.f('ix_call_relationships_caller_symbol_id'), 'call_relationships', ['caller_symbol_id'], unique=False)
    op.create_index(op.f('ix_call_relationships_id'), 'call_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_call_relationships_repository_id'), 'call_relationships', ['repository_id'], unique=False)
    op.drop_constraint(op.f('call_relationships_repository_id_fkey'), 'call_relationships', type_='foreignkey')
    op.drop_constraint(op.f('call_relationships_callee_symbol_id_fkey'), 'call_relationships', type_='foreignkey')
    op.drop_constraint(op.f('call_relationships_caller_symbol_id_fkey'), 'call_relationships', type_='foreignkey')
    op.create_foreign_key(None, 'call_relationships', 'repositories', ['repository_id'], ['id'])
    op.create_foreign_key(None, 'call_relationships', 'symbols', ['caller_symbol_id'], ['id'])
    op.create_foreign_key(None, 'call_relationships', 'symbols', ['callee_symbol_id'], ['id'])
    op.create_foreign_key(None, 'embeddings', 'symbols', ['symbol_id'], ['id'], ondelete='CASCADE')
    op.alter_column('files', 'line_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('repositories', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='repostatus'),
               nullable=False)
    op.alter_column('repositories', 'file_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('repositories', 'symbol_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_repositories_source'), table_name='repositories')
    op.create_index(op.f('ix_repositories_source'), 'repositories', ['source'], unique=False)
    op.alter_column('symbols', 'signature',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_symbols_complexity'), table_name='symbols')
    op.create_index(op.f('ix_symbols_cyclomatic_complexity'), 'symbols', ['cyclomatic_complexity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_cyclomatic_complexity'), table_name='symbols')
    op.create_index(op.f('idx_symbols_complexity'), 'symbols', ['cyclomatic_complexity'], unique=False)
    op.alter_column('symbols', 'signature',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_repositories_source'), table_name='repositories')
    op.create_index(op.f('idx_repositories_source'), 'repositories', ['source'], unique=False)
    op.alter_column('repositories', 'symbol_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('repositories', 'file_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('repositories', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='repostatus'),
               nullable=True)
    op.alter_column('files', 'line_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_constraint(None, 'call_relationships', type_='foreignkey')
    op.drop_constraint(None, 'call_relationships', type_='foreignkey')
    op.drop_constraint(None, 'call_relationships', type_='foreignkey')
    op.create_foreign_key(op.f('call_relationships_caller_symbol_id_fkey'), 'call_relationships', 'symbols', ['caller_symbol_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('call_relationships_callee_symbol_id_fkey'), 'call_relationships', 'symbols', ['callee_symbol_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('call_relationships_repository_id_fkey'), 'call_relationships', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_call_relationships_repository_id'), table_name='call_relationships')
    op.drop_index(op.f('ix_call_relationships_id'), table_name='call_relationships')
    op.drop_index(op.f('ix_call_relationships_caller_symbol_id'), table_name='call_relationships')
    op.drop_index(op.f('ix_call_relationships_callee_symbol_id'), table_name='call_relationships')
    # ### end Alembic commands ###
